alter table CLINIC_VENERINARIAN add constraint FK_CLINIC_VENERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_CLINIC_VENERINARIAN_ON_USER on CLINIC_VENERINARIAN (USER_ID);
